package:
  name: elaspic2
  version: 0.1.2

source:
  path: ../../

build:
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0
  noarch: python

requirements:
  build:
    - python
  run:
    - python
    - biopython =1.78
    - scikit-learn =0.23
    - kmbio =2.1
    - kmtools =0.2
    - pytorch =1.6
    - lightgbm =3.0

test:
  imports:
    - elaspic2

about:
  home: https://gitlab.com/elaspic/elaspic2
  license: MIT License
  summary: "Predicting the effect of mutations on protein folding and protein-protein interaction."
