package:
  name: elaspic-v2
  version: 0.1.0

source:
  path: ../../

build:
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0
  noarch: python

requirements:
  build:
    - python
  run:
    - python
    - biopython =1.78
    - kmbio =2.1.0
    - kmtools =0.2.7

test:
  imports:
    - ev2

about:
  home: https://gitlab.com/ostrokach/elaspic-v2
  license: MIT License
  summary: "Predicting the effect of mutations on protein folding and protein-protein interaction."
