package:
  name: elaspic2
  version: 0.1.5

source:
  path: ../../

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  number: 0
  noarch: python

requirements:
  build:
    - python
  run:
    - python
    - tqdm >=4.50
    - fire >=0.3
    - scikit-learn >=0.23
    - lightgbm >=3.0
    - pytorch =1.7.0
    - biopython >=1.78
    - kmbio >=2.1
    - kmtools >=0.2
    - proteinsolver >=0.1.25
    - transformers >=3.3.1

test:
  imports:
    - elaspic2
  commands:
    - python -m elaspic2 --help

about:
  home: https://gitlab.com/elaspic/elaspic2
  license: MIT License
  summary: "Predicting the effect of mutations on protein folding and protein-protein interaction."
