"""Rosetta system command templates."""

#: Recommended minimization for `ddg_monomer`
MINIMIZE_WITH_CST_SCT = (
    "minimize_with_cst.static.linuxgccrelease "
    "-database {rosetta_db} "
    # Input file
    "-in:file:l /dev/stdin "
    "-in:file:fullatom "
    "-ignore_unrecognized_res "
    #
    "-fa_max_dis 9.0 "
    "-score:weights {score_weights} "
    "-ddg::harmonic_ca_tether 0.5 "
    "-ddg::constraint_weight 1.0 "
    "-ddg::out_pdb_prefix min_cst_0.5 "
    "-ddg::sc_min_only false "
    "{beta}"
)

#: Recommended minimization for `cartesian_ddg`
RELAX_SCT = (
    "relax.linuxgccrelease "
    "-database {rosetta_db} "
    # Input file
    "-in:file:s input.pdb "
    "-in:file:fullatom "
    "-ignore_unrecognized_res "
    #
    "-constraints:cst_fa_file {cst_file} "
    #
    "-native 1a19.pdb "
    "-out:file:silent default.out "
    "-relax:quick"
    "{beta}"
)

#: Arguments `ddg_monomer` and `cartesian_ddg` have in common
DDG_SCT = (
    # The PDB file of the structure on which point mutations should be made
    "-in:file:s '{data.pdb_file}' "
    # The full path to the database is required
    "-database '{rosetta_db}' "
    # Optional -- if there are residues in the input PDB file that Rosetta cannot recognize,
    # ignore them instead of quitting with an error message
    "-ignore_unrecognized_res "
    # Energy function to use
    "-score:weights {weights} "
    # See: https://www.rosettacommons.org/content/ddgmonomer-problem
    "-ignore_zero_occupancy false "
    # ===== ΔΔG arguments =====
    # Optional -- silence all of the log-file / stdout output generated by this protocol
    # "-mute all "
    # The list of point mutations to consider in this run
    "-ddg::mut_file '{mutation_file}' "
    # Write out PDB files for the structures,
    # one for the wildtype and one for the pointmutant for each iteration
    "-ddg::dump_pdbs true "
    # Don't checkpoint
    "-ddg::suppress_checkpointing true "
    # ===== Extra arguments =====
    "{extra} "
)

#: Equivalent to Protocol 3 in Kellog 2011
#: (a bit less accurate than Protocol 16 but much faster)
DDG_MONOMER_SCT = (
    "ddg_monomer.static.linuxgccrelease "
    # Read the input PDB file as a fullatom structure
    "-in::file::fullatom "
    # Optional -- if not given, the default value of 9.0 Angstroms is used
    "-fa_max_dis 9.0 "
    # Use soft-repulsive weight set
    "-ddg::weight_file soft_rep_design "
    # 50 is the recommended number of iterations
    "-ddg::iterations 50 "
    # Repack the residues in an 8 Angstrom shell around the site of the point mutation
    "-ddg::local_opt_only true "
    # Do not report the mean energy
    "-ddg::mean true "
    # Report the minimum energy
    "-ddg::min true "
    # Write output to a silent file
    "-ddg::output_silent true "
) + DDG_SCT

#:
CARTESIAN_DDG_SCT = (
    "cartesian_ddg.static.linuxgccrelease "
    # modify fa_atr and fa_sol behavior, really important for protein stability (default: 6)
    "-fa_max_dis 9.0 "
    # bb dof, suggestion: i-1, i, i+1
    "-bbnbr 1 "
    # Mutation method
    "-ddg::cartesian "
    # can be flexible; 3 is fast and reasonable
    "-ddg::iterations 3 "
) + DDG_SCT

ROSETTA_SYSTEM_COMMANDS = {"cartesian_ddg": CARTESIAN_DDG_SCT, "ddg_monomer": DDG_MONOMER_SCT}
